"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

# Left side
format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

palette = 'tokyo_night'

[character]
vimcmd_symbol = '[N] >>>'
success_symbol = ' [󱞩](blue)'
error_symbol = ' [󱞩](red)'

[directory]
style = 'fg:#e3e5e5 bg:#769ff0'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '.../'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
symbol = ''
style = 'bg:#394260'
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = 'bg:#394260'
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[aws]
disabled = true

[bun]
symbol = ''
style = 'bg:#212736'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ''
style = 'bg:#212736'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kubernetes]
disabled = false
symbol = ' '
style = 'bold blue'
detect_files = []
format = '[$symbol$context( \($namespace\))]($style) '

[rust]
symbol = ''
style = 'bg:#212736'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ''
style = 'bg:#212736'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ''
style = 'bg:#212736'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = '%r'
style = 'bg:#1d2230'
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[palettes.tokyo_night]
red = '#f7768e'
orange = '#ff9e64'
yellow = '#e0af68'
green = '#9ece6a'
teal = '#73daca'
cyan = '#7dcfff'
blue = '#7aa2f7'
magenta = '#bb9af7'
foreground = '#a9b1d6'
comment = '#565f89'
black = '#414868'
bg = '#24283b'
